package com.pa.monitor.refueller.services.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.6.3
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface JNCIServiceEvents
{
    public void Starting();
    public void Completed(JNCOperationResult result);
}
