package com.pa.monitor.refueller.services.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.6.3
//
// Created by Quasar Development 
//
//---------------------------------------------------



public class JNCOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public java.lang.Object Tag;
    public java.lang.String MethodName;

    @Override
    public String toString() {
        return "JNCOperationResult{" +
                "Exception=" + Exception +
                ", Result=" + Result +
                ", Tag=" + Tag +
                ", MethodName='" + MethodName + '\'' +
                '}';
    }
}
