/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_mega_pack_NativeCallsClass */

#ifndef _Included_my_mega_pack_NativeCallsClass
#define _Included_my_mega_pack_NativeCallsClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_mega_pack_NativeCallsClass
 * Method:    printString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_my_mega_pack_NativeCallsClass_printString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     my_mega_pack_NativeCallsClass
 * Method:    printOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_my_mega_pack_NativeCallsClass_printOne
  (JNIEnv *, jobject);

/*
 * Class:     my_mega_pack_NativeCallsClass
 * Method:    printTwo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_my_mega_pack_NativeCallsClass_printTwo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
