package ru.intuit.distributedApplication.firstApplication.lecture6.complex;


/**
* ru/intuit/distributedApplication/firstApplication/lecture6/complex/_BillingServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BillingService.idl
* 23 но€бр€ 2016 г. 21:54:42 YEKT
*/

public class _BillingServiceStub extends org.omg.CORBA.portable.ObjectImpl implements ru.intuit.distributedApplication.firstApplication.lecture6.complex.BillingService
{

  public ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card getCard (String card)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCard", true);
                $out.write_string (card);
                $in = _invoke ($out);
                ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card $result = ru.intuit.distributedApplication.firstApplication.lecture6.complex.CardHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCard (card        );
            } finally {
                _releaseReply ($in);
            }
  } // getCard

  public ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card addNewCard (String personName, String card)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addNewCard", true);
                $out.write_string (personName);
                $out.write_string (card);
                $in = _invoke ($out);
                ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card $result = ru.intuit.distributedApplication.firstApplication.lecture6.complex.CardHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addNewCard (personName, card        );
            } finally {
                _releaseReply ($in);
            }
  } // addNewCard

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:complex/BillingService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _BillingServiceStub
