package ru.intuit.distributedApplication.firstApplication.lecture6.complex;


/**
* ru/intuit/distributedApplication/firstApplication/lecture6/complex/BillingService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BillingService.idl
* 23 но€бр€ 2016 г. 21:54:42 YEKT
*/

public interface BillingService extends BillingServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BillingService
