package ru.intuit.distributedApplication.firstApplication.lecture6.complex;


/**
* ru/intuit/distributedApplication/firstApplication/lecture6/complex/BillingServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BillingService.idl
* 23 но€бр€ 2016 г. 21:54:42 YEKT
*/

public interface BillingServiceOperations 
{
  ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card getCard (String card);
  ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card addNewCard (String personName, String card);
} // interface BillingServiceOperations
