package ru.intuit.distributedApplication.firstApplication.lecture6.complex;

/**
* ru/intuit/distributedApplication/firstApplication/lecture6/complex/CardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BillingService.idl
* 23 но€бр€ 2016 г. 21:54:42 YEKT
*/

public final class CardHolder implements org.omg.CORBA.portable.Streamable
{
  public ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card value = null;

  public CardHolder ()
  {
  }

  public CardHolder (ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ru.intuit.distributedApplication.firstApplication.lecture6.complex.CardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ru.intuit.distributedApplication.firstApplication.lecture6.complex.CardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ru.intuit.distributedApplication.firstApplication.lecture6.complex.CardHelper.type ();
  }

}
