package ru.intuit.distributedApplication.firstApplication.lecture6.complex;


/**
* ru/intuit/distributedApplication/firstApplication/lecture6/complex/CardHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BillingService.idl
* 23 но€бр€ 2016 г. 21:54:42 YEKT
*/

abstract public class CardHelper
{
  private static String  _id = "IDL:complex/Card:1.0";

  public static void insert (org.omg.CORBA.Any a, ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ru.intuit.distributedApplication.firstApplication.lecture6.complex.CardHelper.id (), "Card");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CardStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card)
      return (ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ru.intuit.distributedApplication.firstApplication.lecture6.complex._CardStub stub = new ru.intuit.distributedApplication.firstApplication.lecture6.complex._CardStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card)
      return (ru.intuit.distributedApplication.firstApplication.lecture6.complex.Card)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ru.intuit.distributedApplication.firstApplication.lecture6.complex._CardStub stub = new ru.intuit.distributedApplication.firstApplication.lecture6.complex._CardStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
