package com.pa.kasu.refueller.server;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface DLRIServiceEvents
{
    public void Starting();
    public void Completed(DLROperationResult result);
}
