package ru.intuit.distributedApplication.firstApplication.lecture6.simple;


/**
* ru/intuit/distributedApplication/firstApplication/lecture6/simple/BillingServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BillingService.idl
* 23 íîÿáðÿ 2016 ã. 17:11:20 YEKT
*/

public interface BillingServiceOperations 
{

  // U W! µ ? µ » µ  Q µ CORBA-! U  X µ!! Q X U V U ! µ!  Q! °
  void addNewCard (String personName, String card);
  void addMoney (String card, double money);
  void subMoney (String card, double money);
  double getCardBalance (String card);
} // interface BillingServiceOperations
